#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Cores
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # Sem cor

echo "${BLUE}Executando ESLint...${NC}"
# npm run lint
if [ $? -ne 0 ]; then
    echo "${RED}ESLint encontrou problemas! Corrija antes de fazer commit.${NC}"
    exit 1
fi

echo "${BLUE}Executando testes...${NC}"
npm run test
if [ $? -ne 0 ]; then
    echo "${RED}Alguns testes falharam! Corrija antes de fazer commit.${NC}"
    exit 1
fi

echo "${GREEN}Verificação de código concluída com sucesso! Commit permitido.${NC}"
